// demos/svelte/src/App.svelte
<script lang="ts">
  // Scaffold only — controllers from `@burnt-labs/abstraxion-js` will be wired
  // into Svelte stores in commit 9 of abstraxion_package_restructure.md.
</script>

<main class="m-auto flex min-h-screen max-w-xs flex-col items-center justify-center gap-4 p-6">
  <h1 class="text-2xl font-bold tracking-tighter">ABSTRAXION</h1>
  <p class="text-center text-sm text-gray-400">Svelte demo scaffold</p>
  <p class="text-center text-xs text-gray-500">
    The reference integration wires <code class="rounded bg-white/10 px-1 py-0.5">createController</code>
    from <code class="rounded bg-white/10 px-1 py-0.5">@burnt-labs/abstraxion-js</code>
    to Svelte <code class="rounded bg-white/10 px-1 py-0.5">writable</code> stores.
  </p>
</main>

// apps/demo-app/src/app/page.tsx
"use client";
import Link from "next/link";
import { Button } from "@burnt-labs/ui";
import "@burnt-labs/ui/dist/index.css";

export default function Page(): JSX.Element {
  return (
    <main className="m-auto flex min-h-screen max-w-xs flex-col items-center justify-center gap-4 p-4">
      <h1 className="text-2xl font-bold tracking-tighter text-white">
        ABSTRAXION
      </h1>
      <div className="flex w-full flex-col gap-2">
        <Link href="/ui-less">
          <Button fullWidth structure="outlined">
            CUSTOM UI EXAMPLE
          </Button>
        </Link>
        <Link href="/default-ui">
          <Button fullWidth structure="outlined">
            LEGACY UI EXAMPLE
          </Button>
        </Link>
      </div>
    </main>
  );
}
